name: Build and deploy image-scaleup-performance-evaluation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

        # 'standalone' 옵션은 server.js와 서버가 사용하는 최소한의 의존성만 포함합니다.
        # 따라서 정적 파일을 포함하지 않으며, 이를 제공하기 위해서는
        # 정적 파일을 .next/standalone 내부로 옮겨야 합니다.
      - name: Move static files into standalone
        run: cp -r .next/static .next/standalone/.next/static

        # public/ 에 있는 이미지들도 위와 동일한 이유로 .next/standalone 내부로 옮겨야 합니다.
      - name: Move public folder(assets) into standalone
        run: cp -r public .next/standalone/public

      - name: Zip artifact for deployment
        run: zip -r release.zip .next public package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
            mkdir deploy
            unzip release.zip -d ./deploy/

      - name: Deploy over SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./deploy/*"
          target: "~/image-scaleup-performance-evaluation"

      - name: Restart systemd service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/image-scaleup-performance-evaluation
            npm install --omit=dev
            sudo systemctl restart image-scaleup-performance-evaluation